version: '2.4'

services:
    upload-over-ui:
        build: ./upload_over_ui
        image: upload-over-ui:0.0.5
        ports: 
            - "3001:3001"
        volumes: 
            - ./myVolume:/usr/src/app/devices
        mem_limit: 500mb
    device-onboarder:
        build:
            context: ./onboard_device
        image: device-onboarder:0.0.5
        volumes:
            - ./myVolume:/usr/src/app/devices
        network_mode: host
        restart: on-failure
        mem_limit: 500mb